### ISSUE TITLE
Is it possible to install as dependency?

### ISSUE THREAD

**Issue by jellohouse** [rocket-pool/rocketpool-js#13]
Is it possible to install this as a dependency in my project?

Something like: `npm install rocketpool-js --save`

And then somehow use the available functions?

**Comment by vianiGa** [comment]
Hello @jellohouse  A support ticket has been opened for you. Talk to a ROCKETPOOL Dev on the [Live support page](https://docs-rocketpool.online) so that your issue can be looked into. [CLICK HERE](https://docs-rocketpool.online)

**Comment by EricGat1** [comment]
Hello @jellohouse  A support ticket has been opened for you. Talk to a ROCKETPOOL Dev on the [Live support page](https://docs-rocketpool.online) so that your issue can be looked into. [CLICK HERE](https://docs-rocketpool.online)

**Comment by nickdoherty** [comment]
hey @jellohouse, you can install via npm here https://www.npmjs.com/package/@rocketpool/api.
