### ISSUE TITLE
Tests are outdated

### ISSUE THREAD

**Issue by samparsky** [rocket-pool/rocketpool-js#19]
Some of the tests in this repository are outdated e.g. 

https://github.com/rocket-pool/rocketpool-js/blob/master/src/test/_helpers/minipool.ts#L51 This should be the `rocketPoolMiniFactory` according to the contracts https://github.com/rocket-pool/rocketpool/blob/master/test/_helpers/minipool.js#L73

**Comment by nickdoherty** [comment]
hey @samparsky,

Please see the v1.1 branch, which should have alignment.

https://github.com/rocket-pool/rocketpool-js/blob/495ea14de3e0b314361a378177333bfb48634c2a/src/test/_helpers/minipool.ts#L53

v1.2 is nearing audit completion and will be brought into alignment in the next few weeks.
